//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitTekno.data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponID { get; set; }
        public string CouponCode { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string reference1 { get; set; }
        public string reference2 { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
