//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitTekno.data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int PaymentID { get; set; }
        public string reference1 { get; set; }
        public string reference2 { get; set; }
        public string PaymentType { get; set; }
        public Nullable<bool> Allowed { get; set; }
    }
}
