//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitTekno.data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.ProductComment = new HashSet<ProductComment>();
            this.Images = new HashSet<Images>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductBarcode { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> PriceOutput { get; set; }
        public Nullable<int> OldPriceOutput { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> ProductDescriptionID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImagesID { get; set; }
        public Nullable<int> ProductFeaturesID { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComment> ProductComment { get; set; }
        public virtual ProductDescription ProductDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        public virtual Images Images1 { get; set; }
        public virtual ProductFeatures ProductFeatures { get; set; }
    }
}
