//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitTekno.data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDescription()
        {
            this.ProductDepartment = new HashSet<ProductDepartment>();
            this.Product = new HashSet<Product>();
        }
    
        public int ProductDescriptionID { get; set; }
        public string ProductDescriptionName { get; set; }
        public string Barcode { get; set; }
        public string ProductUrl { get; set; }
        public string Description { get; set; }
        public string ProductImage { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Sale { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> MarkID { get; set; }
        public Nullable<int> PriceOutput { get; set; }
    
        public virtual Mark Mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDepartment> ProductDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
