//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitTekno.data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComment
    {
        public int CommentID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ContactID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
